name: learn-github-actions
on: 
  push:
    paths:
    - 'openidl-mapper/**'
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: cd openidl-mapper
      - run: npm install -g bats
      - run: bats -v
